### ISSUE TITLE
For feedback on the topic "Natural rocks and aggregates" please reply on this message.

### ISSUE THREAD

**Issue by dportilloarreg** [TUDelft-CITG/pre-for-cem#13]
For feedback on the topic "Natural rocks and aggregates" please reply on this message.

_Originally posted by @Mehmetkisa in https://github.com/TUDelft-CITG/pre-for-cem/issues/5#issuecomment-1564174617_
            Looks good to me! Nonetheless, I'd suggest to find alternative OER. While information is ok, the website is an online shop and may be off from TUD's image.

**Comment by ahmedfarhatx22** [comment]
Fixed
